<?php

/**
 * @file
 * Contains layout_config.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function layout_config_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the layout_config module.
    case 'help.page.layout_config':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration form for placing blocks? I hope?') . '</p>';
      return $output;

    default:
  }
}
