layout_config.settings:
  path: '/node/{nid}/layout'
  defaults:
    _form: 'Drupal\layout_config\Form\LayoutConfigSettingsForm'
    _title: 'Edit Layout'
  requirements:
    _permission: 'administer site configuration'
